name: Reuseable Workflow Caller

on:
  workflow_dispatch:
jobs:
    call-reuseable-workflow-path:
        name: Invoke reuseable workflow with relative path
        uses: ./.github/workflows/01-reuseable-workflows-source.yaml
        with:
            foo: bar
            environment: staging
        secrets: 
            inherit
    