name: Composite Action Demo
on:
  workflow_dispatch:
jobs:
    hello-world-1:
      runs-on: ubuntu-latest
      name: One usage of the composite action
      steps:
        - uses: actions/checkout@v4
        - name: Ejecutar  accion hello world
          id: composite-action-instance
          uses: ./actions/base-composite-action.yml
          with:
            who-to-greet: "Marlon"
        - name: Random Number
          env:
            RANDOM_NUMBER: ${{ steps.hello.outputs.random-number }}
          run: |
            echo "Random generado: $RANDOM_NUMBER"