name: Greetings

on: [pull_request_target,issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Gracias por abrir tu primer issue en este repositorio! 🚀"
          pr-message: "🎉 Gracias por enviar tu primer PR, lo revisaremos pronto!"
